export const SpecialComponents = [
  { href: '/components/bentogrid', name: 'Bento Grid' },
  { href: '/components/bottom', name: 'Bottom Navbar', new: true },
  { href: '/components/breadcrumb', name: 'Breadcrumb' },
  { href: '/components/card', name: 'Cards' },
  { href: '/components/carousel', name: 'Carousel' },
  { href: '/components/compliance-dashboard', name: 'Compliance Dashboard', new: true },
  { href: '/components/demo', name: 'Demo' },
  { href: '/components/drawer', name: 'Drawer' },
  { href: '/components/error', name: 'Error' },
  { href: '/components/footers', name: 'Footers' },
  { href: '/components/form', name: 'Form' },
  { href: '/components/hero', name: 'Hero Section' },
  { href: '/components/marquee', name: 'marquee', new: true },
  { href: '/components/modal', name: 'Modal' },
  { href: '/components/navbar', name: 'Navbar' },
  { href: '/components/parallax', name: 'Parallax' },
  { href: '/components/price', name: 'Price' },
  { href: '/components/risk-dashboard', name: 'Risk Dashboard', new: true },
  { href: '/components/skeletonLoader', name: 'Skeleton Loader' },
  { href: '/components/table', name: 'Table' },
  { href: '/components/notification', name: 'Toast '},
];
